=== 0x1a0b/repose/repose-aggregator/components/filters/header-normalization-filter/src/main/resources/META-INF/schema/config/header-normalization-configuration.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
  _=_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_=
  Repose
  _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-
  Copyright (C) 2010 - 2015 Rackspace US, Inc.
  _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-
  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at
  
       http://www.apache.org/licenses/LICENSE-2.0
  
  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
  =_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_=_
  -->


<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:html="http://www.w3.org/1999/xhtml"
           xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning"
           xmlns:xerces="http://xerces.apache.org"
           xmlns:saxon="http://saxon.sf.net/"
           xmlns:hnorm="http://docs.openrepose.org/repose/header-normalization/v1.0"
           targetNamespace="http://docs.openrepose.org/repose/header-normalization/v1.0"
           elementFormDefault="qualified"
           attributeFormDefault="unqualified">

    <!-- Header Normalization Configuration -->
    <xs:element name="header-normalization" type="hnorm:HeaderNormalizationConfig"/>

    <xs:complexType name="HeaderNormalizationConfig">
        <xs:annotation>
            <xs:documentation>
                <html:p>The root config type for the Header Normalization filter configuration file.</html:p>
            </xs:documentation>
        </xs:annotation>

        <xs:all>
            <xs:element name="header-filters" type="hnorm:HeaderFilterList" minOccurs="0" maxOccurs="1">
                <xs:annotation>
                    <xs:documentation>
                        <html:p>
                            Deprecated: This attribute is deprecated. Use request-header-filters instead.
                        </html:p>
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="request-header-filters" type="hnorm:HeaderFilterList" minOccurs="0" maxOccurs="1"/>
            <xs:element name="response-header-filters" type="hnorm:ResponseHeaderFilterList" minOccurs="0" maxOccurs="1"/>
        </xs:all>

        <xs:assert vc:minVersion="1.1"
                   xpathDefaultNamespace="##targetNamespace"
                   test="not(header-filters and request-header-filters)"
                   xerces:message="Cannot define the deprecated header-filters and request-header-filters"
                   saxon:message="Cannot define the deprecated header-filters and request-header-filters"
        />
    </xs:complexType>

    <xs:complexType name="HeaderFilterList">
        <xs:annotation>
            <xs:documentation>
                <html:p>
                    Contains a list of targets that are processed in the order defined. The first target that matches is
                    the only one that modifies the Request headers.
                </html:p>
            </xs:documentation>
        </xs:annotation>

        <xs:sequence>
            <xs:element name="target" type="hnorm:Target" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Target">
        <xs:annotation>
            <xs:documentation>
                <html:p>Defines a Request target with a list of allowed and/or disallowed HTTP Headers.</html:p>
            </xs:documentation>
        </xs:annotation>

        <xs:choice>
            <xs:element name="whitelist" type="hnorm:HttpHeaderList" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="blacklist" type="hnorm:HttpHeaderList" minOccurs="0" maxOccurs="unbounded"/>
        </xs:choice>

        <xs:attribute name="uri-regex" type="xs:string" use="optional">
            <xs:annotation>
                <xs:documentation>
                    <html:p>
                        The uri regex to match against when determining whether or not to apply the filter
                        to the request. If this attribute is null then repose assumes the filtering is
                        performed on all requests with the specified http-methods. If uri-regex and
                        http-methods are both null then the specified header filter is performed on all
                        requests.
                    </html:p>
                </xs:documentation>
            </xs:annotation>
        </xs:attribute>

        <xs:attribute name="http-methods" type="hnorm:HttpMethodList" use="optional" default="ALL">
            <xs:annotation>
                <xs:documentation>
                    <html:p>List of HTTP Methods this target will match on.</html:p>
                </xs:documentation>
            </xs:annotation>
        </xs:attribute>
    </xs:complexType>

    <xs:complexType name="ResponseHeaderFilterList">
        <xs:annotation>
            <xs:documentation>
                <html:p>
                    Contains a list of targets that are processed in the order defined. The first target that matches is
                    the only one that modifies the Response headers.
                </html:p>
            </xs:documentation>
        </xs:annotation>

        <xs:sequence>
            <xs:element name="target" type="hnorm:ResponseTarget" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="ResponseTarget">
        <xs:annotation>
            <xs:documentation>
                <html:p>Defines a Response target with a list of allowed and/or disallowed HTTP Headers.</html:p>
            </xs:documentation>
        </xs:annotation>
        <xs:extension base="Target"/>
        <xs:attribute name="code-regex" type="xs:string" use="optional">
            <xs:annotation>
                <xs:documentation>
                    <html:p>
                        Defines a regular expression that is applied to the Response status code to determine if this
                        target is a match.
                    </html:p>
                </xs:documentation>
            </xs:annotation>
        </xs:attribute>
    </xs:complexType>

    <xs:complexType name="HttpHeaderList">
        <xs:annotation>
            <xs:documentation>
                <html:p>Defines a list of (dis)allowed HTTP Headers.</html:p>
            </xs:documentation>
        </xs:annotation>

        <xs:sequence>
            <xs:element name="header" type="hnorm:HttpHeader" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>

        <xs:attribute name="id" type="xs:string" use="optional">
            <xs:annotation>
                <xs:documentation>
                    <html:p>
                        Deprecated: This attribute is deprecated and will be removed in the next major release.
                    </html:p>
                </xs:documentation>
            </xs:annotation>
        </xs:attribute>
    </xs:complexType>

    <xs:complexType name="HttpHeader">
        <xs:annotation>
            <xs:documentation>
                <html:p>Defines a (dis)allowed HTTP Header.</html:p>
            </xs:documentation>
        </xs:annotation>

        <xs:attribute name="id" type="xs:string" use="required">
            <xs:annotation>
                <xs:documentation>
                    <html:p>The case-insensitive name of the header to match on.</html:p>
                </xs:documentation>
            </xs:annotation>
        </xs:attribute>
    </xs:complexType>

    <xs:simpleType name="HttpMethodList">
        <xs:list itemType="hnorm:HttpMethod"/>
    </xs:simpleType>

    <xs:simpleType name="HttpMethod">
        <xs:annotation>
            <xs:documentation>
                <html:p>
                    The HTTP Method defines a string enumeration of HTTP method verbs as outlined in
                    <a href="http://www.ietf.org/rfc/rfc2616.txt">RFC2616 section 9.</a>
                </html:p>
            </xs:documentation>
        </xs:annotation>

        <xs:restriction base="xs:string">
            <xs:enumeration value="GET"/>
            <xs:enumeration value="DELETE"/>
            <xs:enumeration value="POST"/>
            <xs:enumeration value="PUT"/>
            <xs:enumeration value="PATCH"/>
            <xs:enumeration value="HEAD"/>
            <xs:enumeration value="OPTIONS"/>
            <xs:enumeration value="CONNECT"/>
            <xs:enumeration value="TRACE"/>
            <xs:enumeration value="ALL"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== 0x1a0b/repose/repose-aggregator/tests/functional-tests/src/integrationTest/configs/features/filters/headerNormalization/metrics/response/header-normalization.cfg.xml
<?xml version="1.0" encoding="UTF-8"?>

<header-normalization xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
                      xmlns='http://docs.openrepose.org/repose/header-normalization/v1.0'
                      xsi:schemaLocation='http://docs.openrepose.org/repose/header-normalization/v1.0 ../config/header-normalization-configuration.xsd'>
    <!-- applies to all http methods (GET, POST, PUT, etc) that match the uri-regex -->
    <target uri-regex="/servers/(.*)">
        <response>
            <whitelist>
                <header id="X-Auth-Key"/>
                <header id="X-Auth-User"/>
            </whitelist>
        </response>
    </target>

    <!-- applies only to POST and PUT requests for /resource/(.*)-->
    <target uri-regex="/resource/(.*)" http-methods="POST PUT">
        <response>
            <whitelist>
                <header id="X-Modify"/>
            </whitelist>
        </response>
    </target>

    <!-- this blacklist filter only applies if the request does not match one of the previous targets -->
    <!-- since uri-regex and http-methods are not specified in target the blacklist applies to all http requests
         that don't match the previous two targets -->
    <target>
        <response>
            <blacklist>
                <header id="X-PP-User"/>
                <header id="X-PP-Groups"/>
            </blacklist>
        </response>
    </target>
</header-normalization>
